"""
Django settings for inventory_management project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '''
GDWJQNDvoNnwRda7wA4eGh_BeX7_Svk0HCY-LGNJZB4o_yGEywBmI_SnSKBdWaJy9wV-WzqldqOii09_FQ973KpXkZ1oEonnHBfWhkwLvdRM2afvxbfRAKyfQXjuTfbqALQLcsv8nWnoylMDFWFsp2io9SGyhlvuW7ap0TkEWDcwnLmQIq4GP1WEK_vsMt9pOjYq2DvevPgPHrcIbPpTRYhEA2yCooqPpjIv4NYtgP8WkRIXu68C9WtGkLybifosuXCFUnDRq8jPgZewmSXWEslCYvEH7byL8YrdWLL1vKMT3UyYp-85HWpTRd5_w_WNYBVe9GS8yr2wIp3HC_IhSoTv0LM0v0NQJ_khqC3C4NBMleCnoVyhobKsYn9vsBG1PdkDJFWFadoYmKAKnve-Rk36NW1_7ZFCVrHkUSLaw6WiXpY2omy0cpbqTu6NU1lSvU4ROT0M0-HZj2L23W96LLuWJ91DdnzYAnScG4ypeOjvmBdeLtBaabH2RwU98kw8OGe0V5ceZv5CbQde4pArW6vYUJ78x25_wkGB6FhkIYiPPSD5G77RcgCSjAw4sXww6hkmcJt8jQOXCcinQfZb7vj5mbVA129IR_Cs5UXFFDLfG9SZats6B1v8Zqg9MBetGuteJzwaq4qQuwCvldLLmyWzE3k
'''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'crispy_forms',
    'crispy_bootstrap5'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "inventory/static",  # Update this path based on your project structure
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # This is important for production

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_REDIRECT_URL = '/dashboard'
LOGIN_URL = 'login'

LOW_QUANTITY = 3
